{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: wiki-prometheus
  labels:
#    {{- include "wiki-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: wiki-prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
#    {{- include "wiki-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: wiki-prometheus
{{- end }}