{{- if .Values.grafana.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wiki-chart.fullname" . }}-grafana
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wiki-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "wiki-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
    spec:
      containers:
      - name: grafana
        image: {{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: {{ .Values.grafana.adminUser | quote }}
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.grafana.adminPassword | quote }}
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        - name: GF_SERVER_DOMAIN
          value: ""
        - name: GF_PATHS_PROVISIONING
          value: /etc/grafana/provisioning
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: datasource-config
          mountPath: /etc/grafana/provisioning/datasources
        - name: dashboard-config
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboard-data
          mountPath: /var/lib/grafana/dashboards
        resources:
          {{- toYaml .Values.grafana.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /grafana/api/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /grafana/api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: datasource-config
        configMap:
          name: {{ include "wiki-chart.fullname" . }}-grafana-datasource
      - name: dashboard-config
        configMap:
          name: {{ include "wiki-chart.fullname" . }}-grafana-dashboard-config
      - name: dashboard-data
        configMap:
          name: {{ include "wiki-chart.fullname" . }}-grafana-dashboard
{{- end }}
          